In [6]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [24]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [25]:
class Net(nn.Module):
    def __init__(self):
      super(Net, self).__init__()
      self.fc2 = nn.Linear(2, 2)

    # x represents our data
    def forward(self, x):
      x = self.fc2(x)
      return x

In [26]:
# Equates to one random 28x28 image
random_data = torch.rand((2))

my_nn = Net()
result = my_nn(random_data)
print (result)

tensor([0.3941, 0.0475], grad_fn=<AddBackward0>)


In [27]:
optimizer = optim.SGD(my_nn.parameters(), lr=0.001, momentum=0.9)

In [28]:
# Print model's state_dict
print("Model's state_dict:")
for param_tensor in my_nn.state_dict():
    print(param_tensor, "\t", my_nn.state_dict()[param_tensor].size())

print()

# Print optimizer's state_dict
print("Optimizer's state_dict:")
for var_name in optimizer.state_dict():
    print(var_name, "\t", optimizer.state_dict()[var_name])

Model's state_dict:
fc2.weight 	 torch.Size([2, 2])
fc2.bias 	 torch.Size([2])

Optimizer's state_dict:
state 	 {}
param_groups 	 [{'lr': 0.001, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'params': [0, 1]}]


In [29]:
for param_tensor in my_nn.state_dict():
    print(my_nn.state_dict()[param_tensor])

tensor([[-0.2579,  0.2373],
        [ 0.3449, -0.0019]])
tensor([ 0.5300, -0.1672])


In [30]:
with torch.no_grad():
    my_nn.fc2.weight[0, 0] = 1
print(my_nn.fc2.weight[0, 0])

tensor(1., grad_fn=<SelectBackward>)
